### ISSUE TITLE
Please add a link to the errata to the README

### ISSUE THREAD

**Issue by tony--** [PacktPublishing/Beginning-Cpp-Game-Programming#1]
For some reason, searching for the book title ("Beginning C++ Game Programming") does not work from [the Packt support page](https://www.packtpub.com/books/content/support).  Note that "Beginning C Game Programming" works.

The code downloads and errata page is located at:
https://www.packtpub.com/books/content/support/25367

**Comment by githubce** [comment]
Hi @tony-- 

This issue is resolved now. We have updated our website to fix the issue.
Thanks for finding this out. 

Regards,
