### ISSUE TITLE
window is not drawn without polling event loop

### ISSUE THREAD

**Issue by tony--** [PacktPublishing/Beginning-Cpp-Game-Programming#2]
I'm working through the book using SFML 2.5.1 on a Mac.
The window would not draw using the provided code from Chapter 1.
I had to add a window event polling loop to the game loop in order for the window to be drawn.

I copied the following from [the SFML 2.5 macOS example](https://www.sfml-dev.org/tutorials/2.5/start-osx.php), replacing the "Handle the players' input" block from the provided code:
`
        // Process events
        Event event;
        while (window.pollEvent(event))
        {
            // Close window: exit
            if (event.type == Event::Closed) {
                window.close();
            }
            
            // Escape pressed: exit
            if (event.type == Event::KeyPressed && event.key.code == Keyboard::Escape) {
                window.close();
            }
        }
`

**Comment by crbn-hash** [comment]
same issue here
